public class Bottom2 extends Top{

    /*
    Respuesta: E -> Error de compilación.
        The implied super() call in Bottom2's constructor cannot be satisfied
        because there is no no-arg constructor in Top. A default, no-arg constructor is generated by the
        compiler only if the class has no constructor defined explicitly
     */

    public Bottom2(String s) {
        //super();
        System.out.println("D");
    }

    public static void main(String[] args) {
        new Bottom2("C");
        System.out.println("");
    }
}
